In [1]:
import numpy as np

In [13]:
x = np.matrix([1, -2, 3]).T
y = np.matrix([3, 2, 1]).T
xy_ = np.matmul(x, y.T)
xy_

matrix([[ 3,  2,  1],
        [-6, -4, -2],
        [ 9,  6,  3]])

In [14]:
np.linalg.det(xy_)

0.0

In [16]:
a = np.matrix([[1, 2], [2, 1]])
a

matrix([[1, 2],
        [2, 1]])

In [17]:
np.trace(a)

2

In [18]:
np.linalg.det(a)

-2.9999999999999996

In [24]:
d, V = np.linalg.eig(a)
np.matmul(V, np.matmul(np.diag(d), V.T))

matrix([[1., 2.],
        [2., 1.]])

In [25]:
np.matmul(V, V.T)

matrix([[1., 0.],
        [0., 1.]])

In [26]:
x = np.matrix([[1/np.sqrt(2), 1/np.sqrt(3), 1/np.sqrt(6)], 
               [1/np.sqrt(2), -1/np.sqrt(3), -1/np.sqrt(6)],
               [0, 1/np.sqrt(3), -2/np.sqrt(6)]])
w = np.matrix([[3, 1, 0], [1, 3, 0], [0, 0, 5/2]])

In [28]:
np.linalg.inv(w)

matrix([[ 0.375, -0.125,  0.   ],
        [-0.125,  0.375,  0.   ],
        [ 0.   ,  0.   ,  0.4  ]])

In [29]:
np.matmul(w, np.linalg.inv(w))

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [30]:
np.matmul(x, x.T)

matrix([[ 1.00000000e+00, -2.49570864e-16,  4.58633852e-19],
        [-2.49570864e-16,  1.00000000e+00, -4.58633852e-19],
        [ 4.58633852e-19, -4.58633852e-19,  1.00000000e+00]])

In [31]:
np.linalg.inv(x)

matrix([[ 0.70710678,  0.70710678,  0.        ],
        [ 0.57735027, -0.57735027,  0.57735027],
        [ 0.40824829, -0.40824829, -0.81649658]])

In [33]:
x = np.matrix([[-2, -1, 0], [2, 1, 0], [0, -1, 3], [4, 1, 1]])
x

matrix([[-2, -1,  0],
        [ 2,  1,  0],
        [ 0, -1,  3],
        [ 4,  1,  1]])

In [36]:
c = np.identity(4) - 1/4 * np.ones((4, 4))

In [38]:
np.matmul(c, x)

matrix([[-3., -1., -1.],
        [ 1.,  1., -1.],
        [-1., -1.,  2.],
        [ 3.,  1.,  0.]])

In [39]:
x_ = np.matmul(c, x)
cov = np.matmul(x_.T, x_)
cov

matrix([[20.,  8.,  0.],
        [ 8.,  4., -2.],
        [ 0., -2.,  6.]])

In [65]:
#inv_std = np.linalg.inv(np.diag(np.std(x, axis=0))
inv_var = np.linalg.inv(np.diag(np.array(np.std(x, axis=0))[0]))
z = np.matmul(x_, inv_var)
z

matrix([[-1.34164079, -1.        , -0.81649658],
        [ 0.4472136 ,  1.        , -0.81649658],
        [-0.4472136 , -1.        ,  1.63299316],
        [ 1.34164079,  1.        ,  0.        ]])

In [67]:
1/4 * np.matmul(z.T, z)

matrix([[ 1.00000000e+00,  8.94427191e-01, -5.74134469e-18],
        [ 8.94427191e-01,  1.00000000e+00, -4.08248290e-01],
        [-5.74134469e-18, -4.08248290e-01,  1.00000000e+00]])